version: '3.7'

services:
  web:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=)no(4=sajji^j%eua5pli^+ds%$rzd6pak4h!2b1kg(9bd4b1c
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 192.168.148.129 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=custom_admin
      - SQL_USER=root
      - SQL_PASSWORD=123456
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=custom_admin
    ports:
    - 5432:5432
    restart: always

volumes:
  postgres_data: